### ISSUE TITLE
Where is the refill?

### ISSUE THREAD

**Issue by austinrappa78** [moddayz/uh1d_bin#1]
Cannot find the refill location for a gas canister.

Also, to your install docs please add:

- Extract HelicopterSIB_UH1D folder to the root of P:
  - So you should have folder P:\HelicopterSIB_UH1D
- Requires HelicopterMod_client

**Comment by moddayz** [comment]
4. In the Addons source directory line, specify uh1d_bin-main \ HelicopterSIB_UH1D - the HelicopterSIB_UH1D folder

**Comment by austinrappa78** [comment]
And the refill location for the gas canister?
